Dongpo-App/Dongpo-BE

.github/workflows/workflow_dev.yml

workflow 캐싱 추가

---

.github/workflows/workflow_dev.yml
Dockerfile

캐싱 최적화 - develop

---

.github/workflows/workflow_dev.yml

캐싱 구현 롤백 및 재구현 - develop

---

src/main/java/com/dongyang/dongpo/controller/store/StoreController.java

점포 조회 - Query Param 방식으로 좌표 받아오도록 수정

---

.github/workflows/cicd_workflow.yml

#21 
- main, develop 브랜치 모두 대응하도록 수정
- Gradle 캐싱 삭제 (캐시를 만드는 데 시간이 더 걸림)
- 그 외 최적화

workflow 수정

---

src/main/java/com/dongyang/dongpo/jwt/JwtAuthenticationFilter.java
src/main/java/com/dongyang/dongpo/jwt/JwtTokenProvider.java

#39 
- 토큰 2중 파싱 과정 제거
- JwtTokenProvider 속 사용자 정보 조회 과정 수정
- 그 외 예외 로깅 처리

토큰 인증 오류 해결

---

src/test/java/com/dongyang/dongpo/service/mypage/MyPageServiceTest.java

- 통합 테스트가 아닌 단위 테스트로 동작하도록 재작성

MyPageService 테스트 케이스 작성

---

src/main/java/com/dongyang/dongpo/controller/auth/AuthController.java
src/main/java/com/dongyang/dongpo/service/auth/SocialService.java
src/main/resources/application-credentials.yml

- 개발 환경에서 테스트 쉽게 하기 위함
- .yml 파일에 client_id, redirect_uri 추가해야 함

카카오 로그인 RestAPI 방식 재도입

---

src/main/java/com/dongyang/dongpo/controller/store/StoreController.java
src/main/java/com/dongyang/dongpo/domain/store/Store.java
src/main/java/com/dongyang/dongpo/domain/store/StoreOperatingDay.java
src/main/java/com/dongyang/dongpo/domain/store/StorePayMethod.java
src/main/java/com/dongyang/dongpo/dto/store/StoreUpdateDto.java
src/main/java/com/dongyang/dongpo/repository/store/StoreOperatingDayRepository.java
src/main/java/com/dongyang/dongpo/repository/store/StorePayMethodRepository.java
src/main/java/com/dongyang/dongpo/service/store/StoreService.java

직렬화 오류 해결 & 점포 정보 업데이트 로직 구현

---

src/main/java/com/dongyang/dongpo/domain/store/Store.java
src/main/java/com/dongyang/dongpo/domain/store/StoreVisitCert.java
src/main/java/com/dongyang/dongpo/dto/store/StoreDto.java
src/main/java/com/dongyang/dongpo/dto/store/StoreRegisterDto.java
src/main/java/com/dongyang/dongpo/dto/store/StoreUpdateDto.java

#55 
- Entity 속 boolean 타입 변수들의 타입을 래퍼 클래스인 Boolean 타입으로 변경

boolean 타입 변수의 DTO 매핑 문제 해결

---

src/main/java/com/dongyang/dongpo/jwt/JwtTokenProvider.java

JWT 토큰 생명주기 수정

---

src/main/java/com/dongyang/dongpo/service/auth/SocialService.java

소셜 로그인 정책 수정

---

src/main/java/com/dongyang/dongpo/domain/store/OpenTime.java
src/main/java/com/dongyang/dongpo/domain/store/Store.java
src/main/java/com/dongyang/dongpo/domain/store/StoreVisitCert.java
src/main/java/com/dongyang/dongpo/dto/store/OpenPossibility.java
src/main/java/com/dongyang/dongpo/dto/store/StoreDto.java
src/main/java/com/dongyang/dongpo/repository/store/StoreVisitCertRepository.java
src/main/java/com/dongyang/dongpo/service/location/LocationService.java
src/main/java/com/dongyang/dongpo/service/open/OpenPossibilityService.java
src/main/java/com/dongyang/dongpo/service/store/StoreService.java
src/test/java/com/dongyang/dongpo/service/store/StoreServiceTest.java

#32 
임시로 현재 요일, 시간 (3시간 간격)에 방문인증 성공 여부 1회라도 있을시 오픈가능성 높다고 판단
StoreVisitCert테이블     
DayOfWeek openDay, OpenTime openTime <-- 추가됨

오픈가능성 판단 작성

---

src/main/java/com/dongyang/dongpo/controller/mypage/MyPageController.java
src/main/java/com/dongyang/dongpo/domain/member/Title.java
src/main/java/com/dongyang/dongpo/domain/store/Store.java
src/main/java/com/dongyang/dongpo/dto/bookmark/BookmarkDto.java
src/main/java/com/dongyang/dongpo/dto/mypage/MyPageDto.java
src/main/java/com/dongyang/dongpo/dto/store/ReviewDto.java
src/main/java/com/dongyang/dongpo/dto/store/StoreIndexDto.java
src/main/java/com/dongyang/dongpo/repository/bookmark/BookmarkRepository.java
src/main/java/com/dongyang/dongpo/repository/store/StoreReviewRepository.java
src/main/java/com/dongyang/dongpo/service/mypage/MyPageService.java
src/test/java/com/dongyang/dongpo/service/mypage/MyPageServiceTest.java

#63 #64 
- 칭호 enum 수정
- 마이페이지 기능 추가

마이페이지 기능 수정

---

src/main/java/com/dongyang/dongpo/jwt/JwtTokenProvider.java

[Test] Jwt 토큰 생명 주기 변경

---

src/main/java/com/dongyang/dongpo/controller/bookmark/BookmarkController.java
src/main/java/com/dongyang/dongpo/repository/bookmark/BookmarkRepository.java
src/main/java/com/dongyang/dongpo/service/bookmark/BookmarkService.java

- Store와 Member 정보를 통해 삭제하도록 수정

북마크 삭제 기능 수정

---

src/main/java/com/dongyang/dongpo/domain/store/Store.java
src/main/java/com/dongyang/dongpo/domain/store/StoreReview.java
src/main/java/com/dongyang/dongpo/dto/store/ReviewDto.java
src/main/java/com/dongyang/dongpo/repository/store/StoreReviewRepository.java
src/main/java/com/dongyang/dongpo/service/store/StoreReviewService.java
src/test/java/com/dongyang/dongpo/service/store/StoreReviewServiceTest.java

- 리뷰 정보에 점포 이름도 포함 되도록 수정
- 쿼리 최적화

마이페이지 자신의 리뷰 조회 기능 수정

---

src/main/java/com/dongyang/dongpo/domain/store/StoreReview.java
src/main/java/com/dongyang/dongpo/domain/store/StoreReviewPic.java
src/main/java/com/dongyang/dongpo/dto/store/ReviewDto.java
src/main/java/com/dongyang/dongpo/service/store/StoreReviewService.java

store review 이미지 추가

---

.github/workflows/cicd_workflow.yml
.gitignore
build.gradle
src/main/java/com/dongyang/dongpo/controller/auth/AuthController.java
src/main/java/com/dongyang/dongpo/dto/auth/AppleLoginDto.java
src/main/java/com/dongyang/dongpo/service/auth/AppleLoginService.java
src/main/resources/application-credentials.yml

애플 로그인 구현 테스트

---

src/main/java/com/dongyang/dongpo/domain/member/Member.java
src/main/java/com/dongyang/dongpo/service/member/MemberService.java
src/main/java/com/dongyang/dongpo/service/mypage/MyPageService.java
src/test/java/com/dongyang/dongpo/service/member/MemberServiceTest.java

- JPA 영속성 컨텍스트에 포함되지 않던 문제 해결
- Setter 사용 제거, 별도의 업데이트 메소드 도입

마이페이지 정보 업데이트 로직 수정

---

src/main/java/com/dongyang/dongpo/controller/auth/AuthController.java
src/main/java/com/dongyang/dongpo/dto/auth/ApplePublicKeyDto.java
src/main/java/com/dongyang/dongpo/service/auth/AppleLoginService.java
src/main/java/com/dongyang/dongpo/service/auth/ApplePublicKeyGenerator.java
src/main/java/com/dongyang/dongpo/util/auth/ApplePublicKeyResponse.java
src/main/java/com/dongyang/dongpo/util/auth/AppleTokenParser.java

#30 
- identityToken 방식 로그인 구현
- 탈퇴, 로그아웃 구현 예정

애플 로그인 1차 구현

---

src/main/java/com/dongyang/dongpo/domain/member/Member.java
src/main/java/com/dongyang/dongpo/dto/auth/UserInfo.java
src/main/java/com/dongyang/dongpo/service/auth/SocialService.java

#93 
- 출생연도, 생일 수집 추가
- 추후 연령대 수집 제거 예정

소셜 로그인 수집 정보 변경

---

src/main/resources/application-credentials.yml

[Issue] .yml 수정

---

src/main/java/com/dongyang/dongpo/domain/member/Member.java
src/main/java/com/dongyang/dongpo/dto/auth/UserInfo.java
src/main/java/com/dongyang/dongpo/service/auth/AppleLoginService.java
src/main/java/com/dongyang/dongpo/service/auth/SocialService.java

feat: 소셜 로그인 수집 정보 수정

---

src/main/java/com/dongyang/dongpo/domain/RefreshToken.java

refreshToken key값 id -> email

---

src/test/java/com/dongyang/dongpo/service/store/StoreServiceTest.java

테스트 케이스 오류 수정

---

src/main/java/com/dongyang/dongpo/exception/ErrorCode.java
src/main/java/com/dongyang/dongpo/service/store/StoreService.java

- 방문 인증 요청 시 사용자와 점포 사이의 거리가 100m를 초과할 경우 예외 발생
- ErrorCode 일원화

방문 인증 로직 일부 수정

---

src/main/java/com/dongyang/dongpo/domain/RefreshToken.java
src/main/java/com/dongyang/dongpo/repository/RefreshTokenRepository.java
src/main/java/com/dongyang/dongpo/service/token/TokenService.java
src/test/java/com/dongyang/dongpo/service/token/TokenServiceTest.java

reissue 수정

---

src/main/java/com/dongyang/dongpo/domain/store/StoreReview.java
src/main/java/com/dongyang/dongpo/dto/store/MostVisitMemberResponse.java
src/main/java/com/dongyang/dongpo/dto/store/ReviewDto.java

feat: 점포 상세 조회 응답 수정

---

src/main/java/com/dongyang/dongpo/config/security/SecurityConfig.java
src/main/java/com/dongyang/dongpo/controller/auth/AuthController.java
src/main/java/com/dongyang/dongpo/service/auth/AppleLoginService.java
src/main/java/com/dongyang/dongpo/service/auth/SocialService.java
src/main/java/com/dongyang/dongpo/service/member/MemberService.java

#86 
- 서비스 상 탈퇴 구현 (애플 로그인은 서비스 연결 해제까지)
- 탈퇴 엔드포인트 통합

feat: 회원 탈퇴 구현

---

src/main/java/com/dongyang/dongpo/domain/store/Store.java
src/main/java/com/dongyang/dongpo/dto/store/StoreDto.java
src/main/java/com/dongyang/dongpo/repository/bookmark/BookmarkRepository.java
src/main/java/com/dongyang/dongpo/service/bookmark/BookmarkService.java
src/main/java/com/dongyang/dongpo/service/store/StoreService.java
src/test/java/com/dongyang/dongpo/service/store/StoreServiceTest.java

feat: 점포 상세 조회 응답 필드 추가

---

src/main/java/com/dongyang/dongpo/controller/rank/RankController.java

랭킹 엔드포인트 수정

---

src/main/java/com/dongyang/dongpo/domain/store/StoreReview.java
src/main/java/com/dongyang/dongpo/dto/store/ReviewDto.java

- Double 타입으로 변경하여 소숫점 별점에도 대응하도록 변경
- 리뷰 저장 로직 일부 수정

refactor: 리뷰 별점 데이터 타입 변경

---

src/main/java/com/dongyang/dongpo/controller/store/StoreReviewController.java
src/main/java/com/dongyang/dongpo/domain/store/StoreReview.java
src/main/java/com/dongyang/dongpo/dto/store/ReviewDto.java
src/main/java/com/dongyang/dongpo/dto/store/StoreReviewResponseDto.java
src/main/java/com/dongyang/dongpo/repository/store/StoreReviewRepository.java
src/main/java/com/dongyang/dongpo/service/store/StoreReviewService.java
src/main/java/com/dongyang/dongpo/service/store/StoreService.java

- 조회 가능 상태인 리뷰만 내림차순으로 정렬하여 반환

feat: 특정 점포의 전체 리뷰 조회 구현

---

src/main/java/com/dongyang/dongpo/controller/bookmark/BookmarkController.java
src/main/java/com/dongyang/dongpo/controller/mypage/MyPageController.java
src/main/java/com/dongyang/dongpo/controller/store/StoreController.java
src/main/java/com/dongyang/dongpo/domain/store/Store.java
src/main/java/com/dongyang/dongpo/domain/store/StoreReviewPic.java
src/main/java/com/dongyang/dongpo/dto/bookmark/StoreBookmarkResponseDto.java
src/main/java/com/dongyang/dongpo/dto/store/ReviewDto.java
src/main/java/com/dongyang/dongpo/dto/store/StoreDetailsResponseDto.java
src/main/java/com/dongyang/dongpo/dto/store/StoreDto.java
src/main/java/com/dongyang/dongpo/dto/store/StoreSummaryResponseDto.java
src/main/java/com/dongyang/dongpo/repository/store/StoreReviewPicRepository.java
src/main/java/com/dongyang/dongpo/service/bookmark/BookmarkService.java
src/main/java/com/dongyang/dongpo/service/mypage/MyPageService.java
src/main/java/com/dongyang/dongpo/service/store/StoreReviewPicService.java
src/main/java/com/dongyang/dongpo/service/store/StoreReviewService.java
src/main/java/com/dongyang/dongpo/service/store/StoreService.java
src/test/java/com/dongyang/dongpo/service/mypage/MyPageServiceTest.java
src/test/java/com/dongyang/dongpo/service/store/StoreServiceTest.java

- 정보 조회 API 분산화
- 북마크 로직 수정 (북마크 추가, 제거 시 점포의 북마크 관련 정보 반환)
- 리뷰 등록 로직 일부 수정

refactor: 점포 정보 조회 로직, 북마크 로직 수정

---

src/main/java/com/dongyang/dongpo/domain/member/Member.java
src/main/java/com/dongyang/dongpo/service/auth/SocialService.java
src/main/java/com/dongyang/dongpo/service/member/MemberService.java

- 회원 탈퇴 시 개인 정보 삭제 처리
- 탈퇴 회원 닉네임 변경
- 애플 로그인 사용자의 재가입 불허

refactor: 회원 탈퇴 로직 리팩토링

---

src/main/java/com/dongyang/dongpo/config/security/CustomAuthenticationManager.java
src/main/java/com/dongyang/dongpo/config/security/SecurityConfig.java
src/main/java/com/dongyang/dongpo/controller/auth/AuthController.java
src/main/java/com/dongyang/dongpo/exception/ErrorCode.java
src/main/java/com/dongyang/dongpo/service/auth/AppleLoginService.java
src/main/java/com/dongyang/dongpo/service/auth/SocialService.java
src/main/java/com/dongyang/dongpo/service/member/MemberService.java
src/main/java/com/dongyang/dongpo/service/token/TokenService.java
src/main/java/com/dongyang/dongpo/util/jwt/JwtAuthenticationFilter.java
src/main/java/com/dongyang/dongpo/util/jwt/JwtAuthenticationProvider.java
src/main/java/com/dongyang/dongpo/util/jwt/JwtUtil.java
src/test/java/com/dongyang/dongpo/service/token/TokenServiceTest.java

- Jwt 저장 방식 수정 (Spring Data Redis -> RedisTemplate) - Redis 조작을 더 세밀하게 하기 위함
- 사용자 로그인 시 기존 발행됐던 토큰 만료 처리
- 그 외 Bean 의존성 개선, 로직 중복 최소화 개선

refactor: Jwt 관련 로직 수정
